apiVersion: v1
kind: Service
metadata:
  name: tienda-frontend
  namespace: tienda
spec:
  type: LoadBalancer
  selector:
    app: tienda-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80